name      : cpufreq-plugin
version   : 0.1.0.0
author    : "Chua Hou <human+github@chuahou.dev>"
copyright : "2020 Chua Hou"

extra-source-files:
- README.rst

dependencies:
- base
- process

ghc-options: -Wall

executables:
    cpufreq-plugin:
        main: Main.hs
        source-dirs: src
